/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs/$programId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/datasets': typeof DatasetsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/datasets': typeof DatasetsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets/$datasetId'
    | '/programs/$programId'
    | '/datasets'
    | '/programs'
    | '/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets/$datasetId'
    | '/programs/$programId'
    | '/datasets'
    | '/programs'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/datasets/$datasetId'
    | '/programs/$programId'
    | '/datasets/'
    | '/programs/'
    | '/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
