/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs/$programId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs/$programId/index'
import { Route as ProgramsProgramIdSubmissionsRouteImport } from './routes/programs/$programId/submissions'
import { Route as ProgramsProgramIdSubmissionsSubmissionIdRouteImport } from './routes/programs/$programId/submissions/$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsProgramIdRoute,
} as any)
const ProgramsProgramIdSubmissionsRoute =
  ProgramsProgramIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ProgramsProgramIdRoute,
  } as any)
const ProgramsProgramIdSubmissionsSubmissionIdRoute =
  ProgramsProgramIdSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ProgramsProgramIdSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/datasets': typeof DatasetsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/programs/$programId/submissions': typeof ProgramsProgramIdSubmissionsRouteWithChildren
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/submissions/$submissionId': typeof ProgramsProgramIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/datasets': typeof DatasetsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/programs/$programId/submissions': typeof ProgramsProgramIdSubmissionsRouteWithChildren
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/submissions/$submissionId': typeof ProgramsProgramIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/datasets/': typeof DatasetsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/programs/$programId/submissions': typeof ProgramsProgramIdSubmissionsRouteWithChildren
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/submissions/$submissionId': typeof ProgramsProgramIdSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets/$datasetId'
    | '/programs/$programId'
    | '/datasets'
    | '/programs'
    | '/submissions'
    | '/programs/$programId/submissions'
    | '/programs/$programId/'
    | '/programs/$programId/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets/$datasetId'
    | '/datasets'
    | '/programs'
    | '/submissions'
    | '/programs/$programId/submissions'
    | '/programs/$programId'
    | '/programs/$programId/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/datasets/$datasetId'
    | '/programs/$programId'
    | '/datasets/'
    | '/programs/'
    | '/submissions/'
    | '/programs/$programId/submissions'
    | '/programs/$programId/'
    | '/programs/$programId/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRouteWithChildren
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
    '/programs/$programId/submissions': {
      id: '/programs/$programId/submissions'
      path: '/submissions'
      fullPath: '/programs/$programId/submissions'
      preLoaderRoute: typeof ProgramsProgramIdSubmissionsRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
    '/programs/$programId/submissions/$submissionId': {
      id: '/programs/$programId/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/programs/$programId/submissions/$submissionId'
      preLoaderRoute: typeof ProgramsProgramIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ProgramsProgramIdSubmissionsRoute
    }
  }
}

interface ProgramsProgramIdSubmissionsRouteChildren {
  ProgramsProgramIdSubmissionsSubmissionIdRoute: typeof ProgramsProgramIdSubmissionsSubmissionIdRoute
}

const ProgramsProgramIdSubmissionsRouteChildren: ProgramsProgramIdSubmissionsRouteChildren =
  {
    ProgramsProgramIdSubmissionsSubmissionIdRoute:
      ProgramsProgramIdSubmissionsSubmissionIdRoute,
  }

const ProgramsProgramIdSubmissionsRouteWithChildren =
  ProgramsProgramIdSubmissionsRoute._addFileChildren(
    ProgramsProgramIdSubmissionsRouteChildren,
  )

interface ProgramsProgramIdRouteChildren {
  ProgramsProgramIdSubmissionsRoute: typeof ProgramsProgramIdSubmissionsRouteWithChildren
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
}

const ProgramsProgramIdRouteChildren: ProgramsProgramIdRouteChildren = {
  ProgramsProgramIdSubmissionsRoute:
    ProgramsProgramIdSubmissionsRouteWithChildren,
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
}

const ProgramsProgramIdRouteWithChildren =
  ProgramsProgramIdRoute._addFileChildren(ProgramsProgramIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRouteWithChildren,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
